import { StyleSheet } from 'react-native';

export const formStyles = StyleSheet.create({
  formContainer: {
    width: '100%',
  },
  logCategoryContainer: {
    width: '100%',
    position: 'relative',
    paddingHorizontal: 12,
    paddingTop: 22,
    paddingBottom: 18,
    marginTop: 4,
    marginBottom: 4,
  },
  logCategoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
    rowGap: 16,
  },
  logCategoryGridBtn: {
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  catBtnBorderLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 1.5,
    zIndex: 5,
  },
  catBtnBorderRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 1.5,
    zIndex: 5,
  },
  catBtnBorderBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 1.5,
    zIndex: 5,
  },
  catBtnBorderTopLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: 1.5,
    zIndex: 5,
  },
  catBtnBorderTopRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    height: 1.5,
    zIndex: 5,
  },
  catBtnLegendWrapper: {
    position: 'absolute',
    top: -10,
    alignSelf: 'center',
    paddingHorizontal: 2,
    zIndex: 10,
  },
  catBtnContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logDateSelectorRow: {
    height: 56,
    justifyContent: 'center',
    paddingHorizontal: 12,
    position: 'relative',
    marginBottom: 16,
  },
  logLegendWrapper: {
    position: 'absolute',
    top: -10,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    zIndex: 10,
  },
  logDrawerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
});
